In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv('EXL_EQ_2020_Test_datasets.csv')
df.head()

cust_id  var1  var2  var3  var4  var5  var6  var7  var8    var9  ...  \
0   400001  2871     0     0  1925     0     7     0     1  238388  ...   
1   400002   562     0     0   197     0     3     0     0  136782  ...   
2   400003  4350     0     1  5664     0     8     1    25  336602  ...   
3   400004  7580     0     1  6093     0     8     4    31  501694  ...   
4   400005    58     0     0    53     0     0     0     0   87465  ...   

   var31  var32  var33     var34     var35                 var36  var37  \
0      0      0  other   Pending  Standard  Video/Internet/Voice      N   
1      0      0  other  Inactive  Standard         Internet Only      N   
2      0      1  other  Inactive  Standard        Video/Internet      N   
3      0      1  other    Active  Standard         Internet Only      N   
4      0      0  other    Active  Standard        Video/Internet      N   

   var38           var39  var40  
0    NaN  Single Housing      N  
1  Other  Single Housing      N  
2    NaN  Single Housing      N  
3    NaN  Single Housing      N  
4    NaN  Single Housing      N  

[5 rows x 37 columns]

In [2]:
num_value = {'entertainment_channel1':1, 'entertainment_channel2':2, 'movie_channel1':3, 'news_channel1':4, 'news_channel2':5, 'other':6}
df['var33'] = df['var33'].apply(lambda x: num_value[x])

In [3]:
num_value = {'Active':1, 'Cancelled':2, 'Inactive':3, 'Never':4, 'Pending':5}
df['var34'] = df['var34'].apply(lambda x: num_value[x])

In [4]:
df['var35'].fillna('nan',inplace=True)

In [5]:
num_value = {'nan':0,'CreditCard':1, 'Electronic Transfer':2, 'Standard':3}
df['var35'] = df['var35'].apply(lambda x: num_value[x])

In [6]:
df['var36']=df['var36'].fillna('nan')

In [7]:
num_val={'Homesecurity Only':1, 'Internet Only':2, 'Internet/Homesecurity':3,
       'Internet/Voice':4, 'Internet/Voice/Homesecurity':5, 'Video Only':6,
       'Video/Homesecurity':7, 'Video/Internet':8,
       'Video/Internet/Homesecurity':9, 'Video/Internet/Voice':10,
       'Video/Internet/Voice/Homesecurity':11, 'Video/Voice':12,
       'Video/Voice/Homesecurity':13,'Voice Only':14, 'nan':0}
df['var36'] = df['var36'].apply(lambda x: num_val[x])

In [8]:
df['var37'].fillna('nan',inplace=True)

In [9]:
num_value = {'Y':0, 'N':1,'nan':2}
df['var37'] = df['var37'].apply(lambda x: num_value[x])

In [10]:
df['var38'] = df['var38'].fillna('nan')

In [12]:
df['var39']=df['var39'].fillna('nan')

In [13]:
num= {'nan':5,'Commercial':4,'Single Housing':3, 'Multi Housing':2, 'Exclude mapping':1, 'Other':0}
df['var39'] = df['var39'].apply(lambda x: num[x])

In [14]:
num_value = {'Y':1,'N': 0}
df['var40'] = df['var40'].apply(lambda x: num_value[x])

In [15]:
import numpy as np
df['var24']=df['var24'].fillna(np.mean(df['var24']))

In [16]:
x_test = df.drop(['cust_id','var30'],axis = 1)

In [17]:
df_train = pd.read_csv('EXL_EQ_2020_Train_datasets.csv')


In [18]:
num_value = {'entertainment_channel1':1, 'entertainment_channel2':2, 'movie_channel1':3, 'news_channel1':4, 'news_channel2':5, 'other':6}
df_train['var33'] = df_train['var33'].apply(lambda x: num_value[x])

In [19]:
num_value = {'Active':1, 'Cancelled':2, 'Inactive':3, 'Never':4, 'Pending':5}
df_train['var34'] = df_train['var34'].apply(lambda x: num_value[x])

In [20]:






num_value = {'CreditCard':1, 'Electronic Transfer':2, 'Standard':3}
df_train['var35'] = df_train['var35'].apply(lambda x: num_value[x])

In [21]:
df_train['var37'].fillna('nan',inplace=True)

In [22]:
num_value = {'Y':0, 'N':1,'nan':2}
df_train['var37'] = df_train['var37'].apply(lambda x: num_value[x])

In [23]:
df_train['var38'] = df_train['var38'].fillna('nan')

In [24]:
num_value = {'Agent':3, 'Other':2, 'Self Service':1, 'nan':0}
df_train['var38'] = df_train['var38'].apply(lambda x: num_value[x])

In [25]:
df_train['var39']=df_train['var39'].fillna('nan')

In [26]:
num= {'nan':5,'Commercial':4,'Single Housing':3, 'Multi Housing':2, 'Exclude mapping':1, 'Other':0}
df_train['var39'] = df_train['var39'].apply(lambda x: num[x])

In [27]:
num_value = {'Y':1,'N': 0}
df_train['var40'] = df_train['var40'].apply(lambda x: num_value[x])

In [28]:
num = {'Desktop':1, 'Mobile App':2, 'Mobile Web':3, 'STB':4}
df_train['self_service_platform'] = df_train['self_service_platform'].apply(lambda x: num[x])

In [29]:
import numpy as np
df_train['var24']=df_train['var24'].fillna(np.mean(df['var24']))


In [30]:
df_train['var36']=df_train['var36'].fillna('nan')

In [31]:
num_val={'Homesecurity Only':1, 'Internet Only':2, 'Internet/Homesecurity':3,
       'Internet/Voice':4, 'Internet/Voice/Homesecurity':5, 'Video Only':6,
       'Video/Homesecurity':7, 'Video/Internet':8,
       'Video/Internet/Homesecurity':9, 'Video/Internet/Voice':10,
       'Video/Internet/Voice/Homesecurity':11, 'Video/Voice':12,
       'Video/Voice/Homesecurity':13,'Voice Only':14, 'nan':0}
df_train['var36'] = df_train['var36'].apply(lambda x: num_val[x])

In [32]:
y_train = df_train['self_service_platform']

In [33]:
x_train = df_train.drop(['cust_id','var30','self_service_platform'],axis = 1)

In [34]:
#selecting features

In [35]:
from sklearn.ensemble import ExtraTreesClassifier
model = ExtraTreesClassifier(random_state = 0)
model.fit(x_train,y_train)





C:\Users\SHRADDHA MEHTA\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
                     max_depth=None, max_features='auto', max_leaf_nodes=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
                     oob_score=False, random_state=0, verbose=0,
                     warm_start=False)

In [36]:
z = model.feature_importances_
z

array([0.07216976, 0.00208321, 0.02373479, 0.05685914, 0.00546178,
       0.03010991, 0.01187685, 0.02746032, 0.05879473, 0.01285615,
       0.00883297, 0.04662847, 0.05334802, 0.00778874, 0.0555467 ,
       0.00230979, 0.0590645 , 0.06830939, 0.05207779, 0.02144567,
       0.00207666, 0.03028521, 0.05803091, 0.01861138, 0.02036712,
       0.00286233, 0.03814252, 0.0127739 , 0.03054569, 0.00823528,
       0.03574595, 0.01013224, 0.02306702, 0.02063057, 0.01173451])

In [37]:
idx = np.arange(0, x_train.shape[1])
features_to_keep = idx[z > np.mean(z)]
features_to_keep

array([ 0,  3,  5,  8, 11, 12, 14, 16, 17, 18, 21, 22, 26, 28, 30])

In [38]:
x_feature_selected = x_train.iloc[:,features_to_keep] 
x_feature_selected

var1  var4  var6    var9  var12  var13  var15  var21   var22  var23  \
0       2667  1768     4  291016    109    447    161      9   85287     27   
1        435   515     3  137667     17    135     34      4   60868      4   
2       1520  2280     6  301567    120    453    112     10   92324     26   
3       4393  5731     8  436735    726    797    266     33  117785     71   
4       3587  2493     7  314970    237    614    166     15  100083     46   
...      ...   ...   ...     ...    ...    ...    ...    ...     ...    ...   
299995    53    74     0   59734      0     68      3      0   28748      0   
299996  4083  3244     8  349569    332    691    212     20  108589     57   
299997  2730  2432     4  264067     88    444    103     14   88551     42   
299998  2875  2321     4  295776     81    481    117     11   96020     32   
299999  1533  1249     5  257782    166    315    146      8   92161     29   

        var26  var27  var32  var34  var36  
0           4    153      0      3     10  
1           1     74      0      4      8  
2           5    133      0      3     10  
3          11    208      1      1      2  
4           6    155      0      4      2  
...       ...    ...    ...    ...    ...  
299995      1     12      0      1      2  
299996      7    177      0      5      2  
299997      6    149      0      5      2  
299998      5    116      0      5      8  
299999      3    119      0      4     10  

[300000 rows x 15 columns]

In [39]:
#splitting our selected data

In [40]:
from sklearn.model_selection import train_test_split
x_traint, x_testt, y_traint, y_testt = train_test_split(x_feature_selected,y_train,test_size=0.30, random_state=2)

In [41]:
from sklearn.ensemble import RandomForestClassifier as RF

In [42]:
x_f_test = x_test.drop(['var2','var3','var5','var7','var8','var10','var11','var14','var16','var25','var24','var28','var29','var31','var33','var35','var37','var38','var39','var40'],axis = 1)

In [43]:
#fitting random forest model in selected data

In [44]:
model_RF= RF()
model_RF.fit(x_traint,y_traint)


C:\Users\SHRADDHA MEHTA\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [45]:
y_pre=model_RF.predict(x_testt)
y_pre

array([2, 1, 2, ..., 2, 3, 1], dtype=int64)

In [46]:
RF_Accuracy=np.mean(y_testt == y_pre)
RF_Accuracy

0.7190666666666666

In [47]:
#final output by random forest

In [48]:
y_f_pre = model_RF.predict(x_f_test)
y_f_pre

array([1, 1, 3, ..., 2, 1, 1], dtype=int64)

In [49]:
from sklearn.ensemble import GradientBoostingClassifier

In [50]:
model_gb = GradientBoostingClassifier()
model_gb.fit(x_traint,y_traint)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='auto',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [51]:
y_predict = model_gb.predict(x_testt)
y_predict

array([2, 1, 4, ..., 1, 3, 1], dtype=int64)

In [52]:
GB_Accuracy=np.mean(y_testt == y_predict)
GB_Accuracy

0.7372666666666666

In [ ]:
#final output by gb

In [53]:
y_f_predict = model_gb.predict(x_f_test)
y_f_predict

array([1, 1, 3, ..., 2, 1, 1], dtype=int64)

In [54]:
y_f_predict = pd.DataFrame(y_f_predict)

In [55]:
from xlsxwriter.utility import xl_rowcol_to_cell

In [57]:
output = pd.ExcelWriter('change.xlsx',engine = 'xlsxwriter')
y_f_predict.to_excel(output,index = False,sheet_name = 'report')
output.save()

In [64]:
y_f_predict[0].value_counts()

1    204900
2     48990
3     39282
4      6828
Name: 0, dtype: int64